[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"


[[bin]]
name = "day02"
path = "./rs/day02.rs"

[[bin]]
name = "day04"
path = "./rs/day04.rs"

